[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustls = "0.23.26"

[[bin]]
name = "external_server"
path = "src/external_server.rs"

[[bin]]
name = "client"
path = "src/client.rs"